### ISSUE TITLE
Change shuffle formula.

### ISSUE THREAD

**Issue by WhyFaust** [NotJustin/SkillAutoBalance#2]
I'll just show you an example:
Now he's flipping stupidly one at a time. One for T, one for CT, one for T again, and so on.
But if it's stupid to watch someone get thrown around, it's not right.
Exemple: There are 4 players with levels: 70, 60, 40, 30.
It's gonna spread like this: 70 in T, 60 in CT, 40 in T, 30 in CT
But it's the right order to do it: 70 in T, 60 in CT, 40 in T, 30 in CT
So the balance would be equal.
It's kind of easy to do :3.

**Comment by NotJustin** [comment]
Let me explain the shuffle formula I use now.

7 players: 200, 100, 50, 40, 30, 20, 10

My formula: 
T 200, 20, 10
CT 100, 50, 40, 30

T sum = 230
CT sum = 220

Your formula:
T 200, 50, 30, 10
CT 100, 40, 20

T sum = 290
CT sum = 160

I hope you understand. I used to do it the way you describe, but it sometimes is not a good balance.

edit: Now, there may be bugs. If there is a bug, the formula might not do what I say. I just fixed a bug earlier today.

**Comment by WhyFaust** [comment]
Relatively understandable. But I haven't noticed it yet. I'm gonna make more observations, and then I'm gonna sign out.

**Comment by NotJustin** [comment]
To be fair, my formula has a flaw too.

2000, 500, 400, 300, 200, 200, 200, 100, 100, 50, 30, 20, 10

My formula:
T: 2000, 100, 100, 50, 30, 20, 10
CT: 500, 400, 300, 200, 200, 200,

The person with 2000 is put against all the other best players, and has all the worst players on his team.

Your formula:
T: 2000, 400, 200, 200, 100, 30, 10
CT: 500, 300, 200, 100, 50, 20

This is a good balance.

I will add an option to choose which shuffle formula to use. Or, maybe there is a way for me to have the plugin decide which formula to use on its own?

Edit: Or, I need to learn how to make outliers have less impact. Normalize data? Let's just throw some statistics related words around. I'll figure it out eventually.

**Comment by NotJustin** [comment]
Here is my idea for a new algorithm

- Sort scores.
- Get IQR (Find median. Split scores that are not median into an upper and lower list. Find the median of those two lists. Upper median - lower median = IQR)
- Remove outliers. Any scores that are more than 1.5 * IQR away from the upper or lower quartiles are outliers. Add them to an "Outlier list" (not sure how many std. deviations away I should use)
- Create teams using the remaining players with the "close sums" method
- Add the outliers to teams using the "alternate players" method, starting with the team that has fewer players.

Let's try it on this set:
2000, 500, 400, 300, 200, 200, 200, 100, 100, 50, 30, 20, 10

Upper quartile: 350
Lower quartile: 40
IQR: 310
1.5 * IQR: 465
low outliers would be below: 40 - 465 = -425
high outliers would be above: 350 + 465 = 815
Therefore the only outlier is 2000.

Close sums method on the data set without the outlier:

T: 500, 200, 200, 100, 50, 10
CT: 400, 300, 200, 100, 30, 20,
T-sum: 1060
CT-sum: 1050

The T's and CT's have the same amount of players.
Start with random team. Dump outliers onto the teams using alternating method.
We add the 2000 point player to CT and we are done.

Final teams:
T: 500, 200, 200, 100, 50, 10
CT: 2000, 400, 300, 200, 100, 30, 20

We can try again on the set you gave:

70, 60, 40, 30

Upper quartile: 65
Lower quartile: 35
IQR: 30
1.5 * IQR: 45
low outliers would be below: 35 - 45 = -10
high outliers would be above: 65 + 45 = 110
There are no outliers.

Close sums method on the data set:

T: 70, 40,
CT: 60, 30

This looks like it works well for both examples. I will work on implementing this tomorrow.

**Comment by WhyFaust** [comment]
![image](https://user-images.githubusercontent.com/20227450/83359558-9be8f400-a383-11ea-9b7e-4d54f396d044.png)
nice)
P.S. Autobalance))

**Comment by NotJustin** [comment]
I have noticed this too :(

I am working on it now.

**Comment by NotJustin** [comment]
I am now testing it, I will push what I am testing here, tomorrow if there are no issues I will treat it as a new release and update readme/alliedmodders thread with what is changed.

Make sure to update translations as well!

**Comment by NotJustin** [comment]
Explanation of score types:

Score type 0: K/D
This is standard. But it is sometimes bad for new players.
3:0 = 15:3 = 90:30 = 3.0

Score type 1:  K/D + K/10 - D/20 (changing it from 2*K/D since that is exactly the same as above)
This is using K/D but leaning away from new players.
Example of what some "equal" scores look like:
5:2 = 12:6 = 17:10 = 21:14 = 26:20 = 38:38 = 2.9

Score type 2: K^2/D
More drastic version of type 1. Essentially becomes, sort by kills and ignore deaths.
Example of "equal" scores:
5:2 = 10:8 = 15:18 = 30:72

Score type 3/4/5:
Uses "points", which represents a long-term skill value.
If configured correctly, points are meaningful and using it to balance is effective.
If configured incorrectly, points are meaningless and using it to balance is ineffective.

I will explain based on how it works on my server.

We use gameME.
gameME uses this formula:
Victim Points / Killer Points × Weapon Modifier × 5
We use weapon modifier 0.5, and we set min points exchanged is 1, max 7.
See here: https://docs.google.com/spreadsheets/d/13jZAgrja9F8W7V0WkCZeeC_Z3N3C09xxvWD2N8BQDSc/edit#gid=0

Column A is your points
Column B is the points the person who you kill has
Column C is the amount of points you will gain.

We planned for our players points to be within the range 0 to 2000, since by default players start at 1000. You can look at the leaderboard for our server here, and see that our "points" is a pretty good measure, although few people have surpassed the expectation:
https://stats.mygloveworks.com/players/csgo

The reason these players surpass our expectation is because of point-inflation, which is caused by giving points to players without taking points away from other players. We do that through headshot bonus, and getting 4, 5, 6, 7... kills in a single round. To counter-act inflation, our plan is to reset points every 1-2 months.

One issue I am noticing is, smurf accounts, or people who intentionally tank points one day and then try hard the next, or otherwise just people whose points don't represent their skill. These people mess with the balance. To account for these players, maybe I should combine both points and K/D ratio?

Maybe, keep track of points and K/D ratio. Try to find a relationship between points and K/D. A group of players with similar points should have similar K/D. A player who has similar points as the group, but much higher K/D or much lower, should be considered an outlier. I will think about this, I'm not sure if I'll actually ever implement it because from what I've seen (in servers with gameME at least), it'd be impossible to find a relationship between points and K/D unless they configure their points to be similar to our server. And even then, the high-end and low-end of points is what looks accurate, while the entire middle area varies greatly, and the middle area is where a majority of players are at.

**Comment by WhyFaust** [comment]
![image](https://user-images.githubusercontent.com/20227450/83757788-ad7b1600-a679-11ea-8482-18ded632e049.png)

Scores:
CT: 7,3,8
T:186,78,42
AutoBalance after...

**Comment by NotJustin** [comment]
https://github.com/NotJustin/SkillAutoBalance/issues/8#issuecomment-638976572

This should fix. Autobalance was still swapping incorrect players sometimes before.

**Comment by NotJustin** [comment]
I will add a cvar. It will be the "scale" to multiple IQR by. In what I wrote above, the "scale" was hard-coded as 1.5

Higher scale means a bigger range of numbers to allow in the "closest sums" formula.
Lower scale means more outliers will be found.

After I implement it I will explain what it means.
