### ISSUE TITLE
Balance Problems

### ISSUE THREAD

**Issue by xMaZax** [NotJustin/SkillAutoBalance#25]
If the plugin makes the balance at the end of the round, is obtained if 2 players are left, for example for KT one KT can throw over a T and get this situation that player T rejoice at before the CT.

**Comment by NotJustin** [comment]
The translation is not good, I do not understand.

**Comment by xMaZax** [comment]
Imagine such a situation, there are two players for CT at the end of the round, after which he throws one behind T, it turns out that the player spawns and it turns out 1 CT vs 1 T. Although the players on the T side were already dead.

**Comment by xMaZax** [comment]
Представим такую ситуацию, за КТ два игрока в конце раунда, после чего перекидывает одного за Т, получается что игрок спавнится и получается 1 CT vs 1 T. Хотя за Т сторону игроки были уже  мертвы.

**Comment by xMaZax** [comment]
No need to spawn players at the end of the round immediately with the balance.

**Comment by NotJustin** [comment]
I understand.

You have 2 CT players at the end of the round. The balance occurs. One of these players is moved to T. Now you have 1 T and 1 CT. The player who is moved did not "die". He did not "spawn". I just change his team and his player model from CT to T.

This is a problem if they can shoot each other. That is why, I set it so the player who is moved to the other team has "god mode" and also cannot shoot his gun.

If you do not like this, you can change this convar: `sab_keepplayersalive` to `0`.

**Comment by xMaZax** [comment]
It turns out that if the player is alive, then the balance will kill him, it's bad that the balance is done at the end of the round!!

Получается если игрок жив то при балансе его убьет, это плохо то что баланс делается в конце раунда!!

**Comment by NotJustin** [comment]
When should the balance be done? At the start of the round?

**Comment by xMaZax** [comment]
I would make a balance at the beginning of the round when spawning players.

**Comment by xMaZax** [comment]
Or move it for another team if it is dead at the end of the round.

**Comment by NotJustin** [comment]
Я прошу прощения, если сообщение ниже трудно понять.

There is a problem with making balance at the beginning of the round.

It is because of the order of these events:
1. Players spawn
2. Round starts
3. Balance

As a result, the player's team will be moved while they are alive. This is hard. I would need to teleport players to the correct team's base before the round starts. Also, if I succeed at this, players will be confused about why they are teleporting.

This problem does not exist when I balance at the end of the round. I do not need to teleport players. If a player is alive and I move their team, I put them in a safe mode.

The safe mode is like this:
1. Player cannot attack
2. Player cannot take damage

Do you understand?

**Comment by xMaZax** [comment]
Мое решение: Выбрать игрока которого нужно кинуть в баланс, не убивать его!!, поменять команду игроку в конце раунда и получится то что его заспавнит в новой команде.

My decision: Choose the player you want to throw in the balance, do not kill him!!, change the team to the player at the end of the round and it will turn out that his spawn in a new team.

**Comment by xMaZax** [comment]
https://sourcemod.dev/#/clients/function.ChangeClientTeam

**Comment by NotJustin** [comment]
Пожалуйста, вместо того, чтобы игнорировать то, что я пишу, скажите мне, что вы не понимаете. Печально, что мне приходится писать одно и то же несколько раз.

My plugin does not kill the player, unless you tell the plugin to kill the player. Two days ago, I said to change this convar `sab_keepplayersalive` to `0` because I thought you wanted the player to be killed. If you want the player to stay alive, use `sab_keepplayersalive 1`.

Please, try to understand this example:

The last players alive are 2 CT and 1 T

1 T player dies. CT's win the round. The round ends. Teams are balanced.

There is a chance one of the 2 living CT players will be changed to the other team, T.

When you change the team of a living player using `ChangeClientTeam` the player is killed. It also says this in the URL you sent me.

When you change the team of a living player using `CS_SwitchTeam`, the player is not killed. My plugin does this. However, the player's team is changed immediately. This creates the problem you described at the start. We have 2 CT players, but they are now 1 T and 1 CT.

This is why I have created a safe mode when I change the team of living players. They cannot attack. They cannot take damage. This solves the problem. When the next round starts, they can play normally.

**Comment by NotJustin** [comment]
Мой плагин не убивает игрока, если вы не скажете плагину убить игрока. Два дня назад, я сказал, измените значение этого sab_keepplayersalive на 0, потому что я думал, что вы хотите убить игрока. Если вы хотите, чтобы игрок остался в живых, используйте sab_keepplayersalive 1.

Пожалуйста, попробуйте понять этот пример:

Последние игроки в живых 2 CT и 1 T

1 Т игрок умирает. CT выиграть раунд. Раунд заканчивается. Команды сбалансированы.

Возможно, один из двух живых игроков CT будет переведен в противоположную команду.

Когда вы меняете команду живого игрока с помощью ChangeClientTeam, игрок убивается. Об этом также говорится на сайте, который вы мне прислали.

Я использую другую функцию под названием CS_SwitchTeam. Когда вы меняете команду живого игрока с помощью CS_SwitchTeam, игрок не убивается. Тем не менее, команда игрока меняется немедленно. Это создает проблему, которую вы описали в начале. У нас есть 2 игрока CT, но теперь они 1 T и 1 CT.

Вот почему я создал безопасный режим, когда меняю команду живых игроков. Они не могут атаковать. Они не могут получить урон. Это решает проблему. Когда начинается следующий раунд, они могут играть нормально.

**Comment by xMaZax** [comment]
с sab_keepplayersalive 1 получится то что игрок может переместится и его может убить сразу другой человек за другую команду.

**Comment by NotJustin** [comment]
Игрок не должен быть в состоянии стрелять или получать урон.
Можете ли вы показать мне свой файл в
"./csgo/cfg/sourcemod/SkillAutoBalance.cfg"

**Comment by NotJustin** [comment]
Something is still unclear. 

What happened, 1 or 2?

1. "At the end of the round, with 2 CT's alive, one CT's team is changed to T, and then the other CT proceeded to kill that T"

2. "At the end of the round, with 2 CT's alive, one CT's team is changed to T, and now it is possible for the two players to kill each other"

You are claiming "The player who has changed team can immediately be killed". I am not sure if you are doing this on purpose, or if it is because of the translation. You have never clearly said "I have SEEN the player who has changed team die to another player". Instead, you suggest that it is POSSIBLE for it to happen. In my plugin, I have specifically made it so that it is IMPOSSIBLE for the player to be killed. You claiming that it is possible would be a bug. So please, clearly tell me, have you seen it happen or not.

It is very frustrating to me that after almost 3 days this is still not clear.
