### ISSUE TITLE
[Error] AdminMenu Items

### ISSUE THREAD

**Issue by WhyFaust** [NotJustin/SkillAutoBalance#27]
When you reload the adminmenu, the points from this plugin disappear.
Actually, the problem wasn't that I was reloading the plugin and there were no points. It was that I sometimes noticed they were missing. Well, it turned out afterwards that it was because adminmenu uploading after this plugin or something like that.

**Comment by NotJustin** [comment]
I have not seen this issue. But, I think it occurs because I only checked if adminmenu (and other plugins needed) are added with OnLibraryAdded. Maybe you have the right idea - if plugins load in wrong order, errrors occur.

In upcoming update, I check in OnConfigsExecuted (after all plugins are loaded), if certain libraries exist.

**Comment by NotJustin** [comment]
I have received information from here https://github.com/alliedmodders/sourcemod/pull/4

It is unnecessary for me to check outside of OnLibraryAdded, so I am undoing what I changed here.

I think what you describe is unrelated issue that I have also fixed.
