### ISSUE TITLE
Add on github "plugins" folder

### ISSUE THREAD

**Issue by WhyFaust** [NotJustin/SkillAutoBalance#3]
It's kind of possible to make the sp file compile and publish itself, but I don't know how.
But you can also just compile after any changes. I just think it would be very difficult for everybody to compile by themselves and so on and so forth.

**Comment by NotJustin** [comment]
I am just worried if this plugin does not work on older versions of sourcemod.

**Comment by NotJustin** [comment]
What I mean is, if someone uses the .smx but they are missing some files, it will be a headache for me to figure out what their issue is.

If they try to compile and fail, they can see why and fix themselves, or come to me with the issue and I can easily help.

**Comment by bubobih** [comment]
anyway i cant compile 

https://i.imgur.com/rydTMY9.png

im trying like 30min.... much much complicated. add smx its easyer

**Comment by NotJustin** [comment]
This is my mistake for not trying to compile before merging. I get the same issue. I am sorry that you wasted 30 minutes on this @bubobih 

Also @baferpro this is what I mean, it is easy for me to figure out issue if other people try to compile. Although I should have found this problem myself :( So maybe, I should add plugins folder and smx if the issue will only occur if the plugin is missing includes?

The problem is, author of nc_rpg should be putting those include's in his plugin's .sp file, not in the include. By putting it in the include file, it will force me to add all his other includes, which is not needed because I do not run his plugin and most people who use my plugin will not run his plugin either (since it is a private plugin).

There is a difference between an include file for an extension and a plugin.
An extension include (sdktools for example) must have all other includes inside of it. There is nowhere else to put them - there is no plugin paired with sdktools as it is an extension.
A plugin include should not have any other includes in it, because they can all be written in the original plugin's file. Anyone who uses the plugin must have all of the includes. Anyone who does not use the plugin will not.

If baferpro attempts to add the missing include files from nc_rpg I will not allow it. Until I can confirm that the original plugin has the appropriate includes in it I will not allow it. The author of that plugin must fix his issue.

**Comment by WhyFaust** [comment]
I'm sorry I didn't see that coming. Anyway, I'd rather just make a branch for myself and mine. It'll be easier that way. I'll just fill in your updates at my place. 
P.S. This plugin will go public for a week or so, and I think it'll be possible if there's something to update. If you say so.

**Comment by NotJustin** [comment]
Added plugins folder.

**Comment by NotJustin** [comment]
@baferpro 

I see it is public now. I am trying to find exactly what is needed in order to compile.

`#include <NCIncs/ncrpg_XP_Credits>` is the only one that has the native you are using.
This does not work because another native in that include file has `NCRPG_EventMode`.

`#include <NCIncs/ncrpg_Constants>` has `NCRPG_EventMode`.

Now the plugin compiles. I wish I did not have to include both, but it is better than including everything.

Can you tell me if this works? I will push commit in a few minutes.

edit: It does not work.
`L 06/05/2020 - 22:08:07: [SM] Unable to load plugin "skillautobalance.smx": Native "NCRPG_GetLevel" was not found`

This is because it is not marked as optional - only nc_rpg.inc marks it as optional. I will not push with this change yet.
